### ISSUE TITLE
Synchronisation failed, dropping peer

### ISSUE THREAD

**Issue by Ivanello** [XinFinOrg/XinFin-Node#58]
Hi Guys have an issue with syncing node
its staring , starting synk but in some point give an errors

```
WARN [11-12|10:19:38] Synchronisation failed, dropping peer peer=e80ecd700a4f13f5 err="retrieved hash chain is invalid"
You've encountered a sought after, hard to reproduce bug. Please report this to the developers <3


index allocation went beyond available resultCache space
/work/xdcchain/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/queue.go:510
goroutine 543700 [running]:
runtime/debug.Stack(0x60, 0x0, 0x0)
/usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
/usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/ethereum/go-ethereum/common.Report(0xc008565a28, 0x1, 0x1)
/work/xdcchain/build/_workspace/src/github.com/ethereum/go-ethereum/common/debug.go:35 +0x1a5
github.com/ethereum/go-ethereum/eth/downloader.(*queue).reserveHeaders(0xc020779c00, 0xc00b28def0, 0x80, 0xc021c04e70, 0xc0051a88c8, 0xc021c04ea0, 0xc021c04ed0, 0x10a81c0, 0x49aca8, 0xc0051a5c08, ...)
/work/xdcchain/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/queue.go:510 +0x6cb
github.com/ethereum/go-ethereum/eth/downloader.(*queue).ReserveBodies(0xc020779c00, 0xc00b28def0, 0x80, 0x0, 0xc00b28de00, 0x0, 0x0)
/work/xdcchain/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/queue.go:462 +0xeb
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).fetchParts(0xc000602c00, 0x12488c0, 0xc00011b3f0, 0xc005070840, 0xc008565e90, 0xc0051b88c0, 0xc008565e80, 0xc008565ef0, 0xc008565ee0, 0xc008565ed0, ...)
/work/xdcchain/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1115 +0x866
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).fetchBodies(0xc000602c00, 0x1401c85, 0x4563d6, 0x10aa1a0)
/work/xdcchain/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:936 +0x307
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer.func4(0x12488c0, 0xc000192050)
/work/xdcchain/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:466 +0x36
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1(0xc03312be30, 0xc00a4c29c0, 0xc022784fc0)
/work/xdcchain/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:486 +0x53
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
/work/xdcchain/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:486 +0xc3
BUG! PLEASE REPORT
```
run in docker on image
`image: xinfinorg/xinfinnetwork:xdc_mainnet_ignoreBlock`

**Comment by Ivanello** [comment]
after some restarts of nod i received
`
...[240 79 50 196 111 26 22 102 59 199 246 64 155 53 179 63 61 170 154 3]]" penList=[]
ERROR[11-15|11:35:18] 
########## BAD BLOCK #########
Chain config: {ChainID: 50 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 4 Constantinople: <nil> Engine: XDPoS}

Number: 28270800
Hash: 0x41105d8d5c0729b24c24980bebe1f7d9c61dbd7fbefc4fd921deb20242762681


Error: invalid signer list on checkpoint block
##############################
 
WARN [11-15|11:35:18] Synchronisation failed, dropping peer    peer=20d59e5f058cb8f6 err="retrieved hash chain is invalid"
WARN [11-15|11:35:18] Synchronisation failed, dropping peer    peer=826a7e2a038e4f1d err="action from bad peer ignored"
ERROR[11-15|11:35:21] Masternodes lists are different in checkpoint header and snapshot number=28270800 masternodes_from_checkpoint_header="[[3 217 225 122 227 255 44 103 18 228 78 37 176 154 197 238 145 246 201 255]...`

**Comment by AnilChinchawale** [comment]
@Ivanello Thank you for reporting the error, Team has fixed this issue and it's ready to publish in MainNet Network soon, Meanwhile, you can use the below snapshot to download the latest blocks chain data.

Snapshot link :- https://download.xinfin.network/xdcchain.tar

**Comment by Ivanello** [comment]
thanks a lot, Guys it syncing now, 
with errors but syncing
```
#### BUG! PLEASE REPORT ####
WARN [11-17|13:39:10] Synchronisation failed, dropping peer    peer=ba126896dac81dcf err="retrieved hash chain is invalid"
You've encountered a sought after, hard to reproduce bug. Please report this to the developers <3 https://github.com/ethereum/go-ethereum/issues
index allocation went beyond available resultCache space
/work/xdcchain/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/queue.go:510
goroutine 6557988 [running]:
runtime/debug.Stack(0x60, 0x0, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/ethereum/go-ethereum/common.Report(0xc00eb43a28, 0x1, 0x1)
        /work/xdcchain/build/_workspace/src/github.com/ethereum/go-ethereum/common/debug.go:35 +0x1a5
github.com/ethereum/go-ethereum/eth/downloader.(*queue).reserveHeaders(0xc02adc6200, 0xc006f56f00, 0x80, 0xc04cac85a0, 0xc02ad65088, 0xc04cac85d0, 0xc04cac8600, 0x10a81c0, 0x7000105, 0x0, ...)
        /work/xdcchain/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/queue.go:510 +0x6cb
github.com/ethereum/go-ethereum/eth/downloader.(*queue).ReserveBodies(0xc02adc6200, 0xc006f56f00, 0x80, 0x0, 0xc006f56f00, 0x0, 0x0)
        /work/xdcchain/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/queue.go:462 +0xeb
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).fetchParts(0xc000329200, 0x12488c0, 0xc000307480, 0xc02ae265a0, 0xc00eb43e90, 0xc02ae04b60, 0xc00eb43e80, 0xc00eb43ef0, 0xc00eb43ee0, 0xc00eb43ed0, ...)
        /work/xdcchain/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1115 +0x866
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).fetchBodies(0xc000329200, 0x23fd98b, 0x4563d6, 0x10aa1a0)
        /work/xdcchain/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:936 +0x307
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer.func4(0xc050222cf0, 0x0)
        /work/xdcchain/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:466 +0x36
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1(0xc02bd8cf20, 0xc02cc25980, 0xc03d3ba480)
        /work/xdcchain/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:486 +0x53
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
        /work/xdcchain/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:486 +0xc3
#### BUG! PLEASE REPORT ####
WARN [11-17|13:41:33] Synchronisation failed, dropping peer    peer=063d658e4980681e err="retrieved hash chain is invalid"
You've encountered a sought after, hard to reproduce bug. Please report this to the developers <3 https://github.com/ethereum/go-ethereum/issues
index allocation went beyond available resultCache space
/work/xdcchain/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/queue.go:510
goroutine 6810910 [running]:
runtime/debug.Stack(0x60, 0x0, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x9d
runtime/debug.PrintStack()
        /usr/local/go/src/runtime/debug/stack.go:16 +0x22
github.com/ethereum/go-ethereum/common.Report(0xc02a4dfa28, 0x1, 0x1)
        /work/xdcchain/build/_workspace/src/github.com/ethereum/go-ethereum/common/debug.go:35 +0x1a5
github.com/ethereum/go-ethereum/eth/downloader.(*queue).reserveHeaders(0xc02adc6200, 0xc00a4543c0, 0x80, 0xc04ad08c90, 0xc02ad65088, 0xc04ad08cc0, 0xc04ad08cf0, 0x10a81c0, 0x8010101, 0x0, ...)
        /work/xdcchain/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/queue.go:510 +0x6cb
github.com/ethereum/go-ethereum/eth/downloader.(*queue).ReserveBodies(0xc02adc6200, 0xc00a4543c0, 0x80, 0x0, 0xc00a454300, 0x0, 0x0)
        /work/xdcchain/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/queue.go:462 +0xeb
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).fetchParts(0xc000329200, 0x12488c0, 0xc000307480, 0xc02ae265a0, 0xc02a4dfe90, 0xc02ae04b60, 0xc02a4dfe80, 0xc02a4dfef0, 0xc02a4dfee0, 0xc02a4dfed0, ...)
        /work/xdcchain/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1115 +0x866
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).fetchBodies(0xc000329200, 0x2403bfb, 0xc0097c3790, 0x9a3c4d)
        /work/xdcchain/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:936 +0x307
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).syncWithPeer.func4(0xc013d2ce10, 0x41)
        /work/xdcchain/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:466 +0x36
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1(0xc0228c2cb0, 0xc045365aa0, 0xc045856f40)
        /work/xdcchain/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:486 +0x53
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
        /work/xdcchain/build/_workspace/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:486 +0xc3
#### BUG! PLEASE REPORT ####
WARN [11-17|13:43:41] Synchronisation failed, dropping peer    peer=e54c3930bd852342 err="retrieved hash chain is invalid"
```
